-- MySQL Workbench Synchronization
-- Generated: 2015-09-16 08:01
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: Tony

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

ALTER TABLE `ying`.`hs_index_code` 
CHANGE COLUMN `code` `code_index` VARCHAR(6) NOT NULL COMMENT 'index code' ,
CHANGE COLUMN `name` `name_index` VARCHAR(18) NULL DEFAULT NULL COMMENT 'index name' ,
CHANGE COLUMN `flag_hs_s` `flag_hs_s` VARCHAR(10) NULL DEFAULT NULL COMMENT 'flag in table hs_s' , RENAME TO  `ying`.`hs_index_info` ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
