-- DROP TABLE `ying`.`hs_s_rt_mv_EM`;
CREATE TABLE `hs_s_rt_mv_EM` (
  `code` varchar(6) NOT NULL COMMENT 'code',
  `TimeSlot` datetime NOT NULL,
  `m5c` decimal(6,2) unsigned DEFAULT NULL COMMENT 'close 5 periods均线',
  `m10c` decimal(6,2) unsigned DEFAULT NULL COMMENT 'close 10 periods均线',
  `m20c` decimal(6,2) unsigned DEFAULT NULL COMMENT 'close 20 periods均线',
  `m30c` decimal(6,2) unsigned DEFAULT NULL COMMENT 'close 30 periods均线',
  `m60c` decimal(6,2) unsigned DEFAULT NULL COMMENT 'close 60 periods均线',
  `m120c` decimal(6,2) unsigned DEFAULT NULL COMMENT 'close 120 periods均线',
  `m5v` int(10) unsigned DEFAULT NULL COMMENT 'volume 5 periods均线',
  `m10v` int(10) unsigned DEFAULT NULL COMMENT 'volume 10 periods均线',
  `m20v` int(10) unsigned DEFAULT NULL COMMENT 'volume 20 periods均线',
  `m30v` int(10) unsigned DEFAULT NULL COMMENT 'volume 30 periods均线',
  `m60v` int(10) unsigned DEFAULT NULL COMMENT 'volume 60 periods均线',
  `m120v` int(10) unsigned DEFAULT NULL COMMENT 'volume 120 periods均线',
  `m5a` int(10) unsigned DEFAULT NULL COMMENT 'amount 5 periods均线',
  `m10a` int(10) unsigned DEFAULT NULL COMMENT 'amount 10 periods均线',
  `m20a` int(10) unsigned DEFAULT NULL COMMENT 'amount 20 periods均线',
  `m30a` int(10) unsigned DEFAULT NULL COMMENT 'amount 30 periods均线',
  `m60a` int(10) unsigned DEFAULT NULL COMMENT 'amount 60 periods均线',
  `m120a` int(10) unsigned DEFAULT NULL COMMENT 'amount 120 periods均线',
  `m5wb` decimal(6,2) unsigned DEFAULT NULL COMMENT 'WeiBi 5 periods均线',
  `m10wb` decimal(6,2) unsigned DEFAULT NULL COMMENT 'WeiBi 10 periods均线',
  `m20wb` decimal(6,2) unsigned DEFAULT NULL COMMENT 'WeiBi 20 periods均线',
  `m30wb` decimal(6,2) unsigned DEFAULT NULL COMMENT 'WeiBi 30 periods均线',
  `m60wb` decimal(6,2) unsigned DEFAULT NULL COMMENT 'WeiBi 60 periods均线',
  `m120wb` decimal(6,2) unsigned DEFAULT NULL COMMENT 'WeiBi 120 periods均线',
  `m5lb` decimal(6,2) unsigned DEFAULT NULL COMMENT 'LiangBi 5 periods均线',
  `m10lb` decimal(6,2) unsigned DEFAULT NULL COMMENT 'LiangBi 10 periods均线',
  `m20lb` decimal(6,2) unsigned DEFAULT NULL COMMENT 'LiangBi 20 periods均线',
  `m30lb` decimal(6,2) unsigned DEFAULT NULL COMMENT 'LiangBi 30 periods均线',
  `m60lb` decimal(6,2) unsigned DEFAULT NULL COMMENT 'LiangBi 60 periods均线',
  `m120lb` decimal(6,2) unsigned DEFAULT NULL COMMENT 'LiangBi 120 periods均线',
  PRIMARY KEY (`code`,`TimeSlot`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
